name: coinmerce
description: "Coinmerce Crypto app"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  fl_chart: ^0.66.2

  cupertino_icons: ^1.0.8
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  go_router: ^15.1.3
  flutter_bloc: ^9.1.1
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  freezed_annotation: ^3.0.0
  device_frame_plus: ^1.5.0
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  sentry_flutter: ^8.14.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  intl_utils: ^2.8.10
  build_runner: ^2.4.15
  retrofit_generator: ^9.2.0
  json_serializable: ^6.0.1
  freezed: ^3.0.6
  flutter_gen_runner: ^5.4.0

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
